jobs:
- job: tests
  trigger: pull_request
  targets:
    - fedora-latest-x86_64
    - fedora-latest-aarch64
    - fedora-rawhide-x86_64
    - fedora-rawhide-aarch64
  skip_build: true
  tmt_plan: "/e2e/plans/keylime-mcp-main$"
