---
name: golangci-lint

"on":
  push:
    paths-ignore:
      - '**.md'
      - '**.sh'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.sh'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    continue-on-error: ${{ ! matrix.stable }}
    strategy:
      matrix:
        os:
          - fedora:latest
        stable: [true]
        include:
          - os: quay.io/fedora/fedora:rawhide
            stable: false
    steps:
      - uses: actions/checkout@v5

      - name: Show OS information
        run: cat /etc/os-release

      - name: Install Go
        run: dnf -y install golang

      - name: Show Go version
        run: go version

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint -v run ./...

    container:
      image: ${{matrix.os}}
      env:
        DISTRO: ${{matrix.os}}
        GOPATH: /root/go
        PATH: /root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
