---
name: gosec

"on":
  push:
    paths-ignore:
      - '**.md'
      - '**.sh'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.sh'

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Show OS information
        run: cat /etc/os-release

      - name: Install Go
        run: dnf -y install golang

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec -exclude=G706 ./...

    container:
      image: fedora:latest
      env:
        GOPATH: /root/go
        PATH: /root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
