---
name: staticcheck

"on":
  push:
    paths-ignore:
      - '**.md'
      - '**.sh'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.sh'

jobs:
  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Show OS information
        run: cat /etc/os-release

      - name: Install Go
        run: dnf -y install golang

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

    container:
      image: fedora:latest
      env:
        GOPATH: /root/go
        PATH: /root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
